### ISSUE TITLE
Sync Job will only sync 2 products and 2 ingredients

### ISSUE THREAD

**Issue by Robert-H-Leonard** [ikenom/contentful-service#13]
**Background**

In `SynchronizerJob` we query contentful and limit the response to only two entries:

Ingredients Sync: https://github.com/ikenom/contentful-service/blob/master/app/jobs/synchronizer_job.rb#L18

Meal Sync: https://github.com/ikenom/contentful-service/blob/master/app/jobs/synchronizer_job.rb#L25

**Acceptance Criteria**

- We should be able to clear the database and run a sync job with more than two ingredients and more than two meals.
- Probably need a test case for this.

**Comment by iomekam** [comment]
That's not what that number stands for.`include: 2` allows the API to resolve links to other related entries. We will get all `ingredients` and all `meals` currently.
